name: deploy-web-server

on: 
    push:
        branches:
        - node_docker_nginx

jobs:
    deploy: 
        name: deploy in droplet 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
      
            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
            - name: Deploy to server droplet
              run: | 
                doctl compute ssh testing-server '
                    cd docker-nginx && 
                    get fetch --all && 
                    git reset --hard origin/node_docker_nginx &&
                    git pull origin node_docker_nginx &&
                    docker-compose up -d --build
                '
