name: deploy-web-server

on: 
    push:
        branches:
        - node_docker_nginx

jobs:
    deploy: 
        name: deploy in droplet 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
      
            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
            - name: List Droplets
              run: |
                doctl compute droplet list
